name: Greetings

on: pull_request

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-validation:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Pull request size and stability labels
        uses: actions/labeler@v4
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Conventional Label
        uses: bcoe/conventional-release-labels@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored_types: '["chore","pr"]'
          type_labels: '{"feat": "feature", "fix": "fix", "bug": "fix", "doc": "documentation", "ci": "ci", "chore": "chore", "breaking": "breaking", "BREAKING CHANGE": "breaking"}'

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ github.head_ref }}

      - name: Conventional Changelog Update
        continue-on-error: true
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          skip-on-empty: "false"
          git-branch: refs/heads/${{ github.head_ref }}

      - name: Checkout pr
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Comment PR
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          message: |
            # Current changelog

            ${{ steps.changelog.outputs.clean_changelog }}
          comment_tag: "# Current changelog"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  greeting:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ github.token }}
        issue-message: "Thanks for submitting your first issue"
        pr-message: "Thanks for opening your first PR"
    - name: PR Greeting
      uses: bcgov-nr/action-pr-description-add@v0.0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        add_markdown: |
          ---
          Thanks for the PR!
          
          Once merged, code will be promoted and handed off to following workflow run.
          [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run package

  test:
    needs: 
      - build
      - pr-validation
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setting up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@paulushcgcj'

      - name: Running CI
        run: npm ci
      - name: Setting version
        run: npm version ${{ needs.pr-validation.outputs.version }}-PR${{ github.event.number }} --no-git-tag-version

      - name: Publishing content
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Test action
        id: action
        uses: ./
        with:
          type: maven
          name: io.github.paulushcgcj.sample.sample-app
          version: ${{ needs.pr-validation.outputs.version }}-PR${{ github.event.number }}
